version: '3.7'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - 15433:5432
    volumes:
      - data-postgres:/var/lib/postgresql/data

volumes:
  data-postgres:
    name: wawefl
